name: Auto-create PR for feature branches

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "auto-create-pr placeholder"



