---
name: Auto-create PR for feature branches

on:
  push:
    branches:
      - 'feature/**'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create or update PR
        uses: actions/github-script@v7
        env:
          PR_TOKEN: ${{ secrets.PR_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          # We still provide github.token here so the action has a token available.
          github-token: ${{ github.token }}
          script: |
            const { Octokit } = require('@octokit/rest');

            // Prefer a PAT provided via PR_TOKEN, otherwise fall back to the
            // repository-scoped GITHUB_TOKEN. Reading the secret via env avoids
            // using secrets in YAML expressions which some linters/validators
            // flag as invalid context access.
            const token = process.env.PR_TOKEN || process.env.GITHUB_TOKEN;
            const oct = new Octokit({ auth: token });

            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const head = context.ref.replace('refs/heads/', '');
            const base = 'main';
            const title = `Auto PR from ${head}`;
            const body = `This pull request was automatically created from branch **${head}**.`;

            // Check for existing open PR from this head
            const existing = await oct.pulls.list({
              owner,
              repo,
              head: `${owner}:${head}`,
              base,
              state: 'open',
            });

            if (existing.data && existing.data.length > 0) {
              core.info(`Found existing PR: ${existing.data[0].html_url}`);
              return existing.data[0].html_url;
            }

            const pr = await oct.pulls.create({
              owner,
              repo,
              head,
              base,
              title,
              body,
            });

            core.info(`Created PR: ${pr.data.html_url}`);
            return pr.data.html_url;
