---
name: Auto-merge PR when labeled

on:
  pull_request:
    types:
      - labeled

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Check label and merge (placeholder)
        run: echo "auto-merge-pr placeholder"
