name: Auto-merge PR when labeled

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Check label and merge
        uses: actions/github-script@v7
        with:
          # Use a Personal Access Token stored in repository secrets named PR_TOKEN because
          # some repositories restrict the permissions of the built-in GITHUB_TOKEN.
          github-token: ${{ secrets.PR_TOKEN }}
          script: |
            const label = context.payload.label.name;
            if (label !== 'automerge') {
              core.info('Label is not automerge; exiting.');
              return;
            }
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const prNumber = context.payload.pull_request.number;

            // Merge the PR
            const { data: mergeResult } = await github.rest.pulls.merge({ owner, repo, pull_number: prNumber, merge_method: 'squash' });
            core.info(`Merged PR #${prNumber}: ${mergeResult.sha}`);
            return mergeResult;
