---
name: Discord notifications

on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on push (placeholder)
        if: github.event_name == 'push'
        run: echo "discord-notify placeholder for push"

      - name: Notify on PR merged (placeholder)
        if: github.event.pull_request.merged == true
        run: echo "discord-notify placeholder for pr_merged"
