name: Discord notifications

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify on push
        if: github.event_name == 'push'
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ref=${GITHUB_REF#refs/heads/}
          commit_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          content="**Update** in ${GITHUB_REPOSITORY}\nBranch: \`${ref}\`\nPusher: ${GITHUB_ACTOR}\nCommit: <${commit_url}>"
          json=$(printf '%s' "{\"content\":\"$content\"}")
          curl -s -H "Content-Type: application/json" -d "$json" "$WEBHOOK"

      - name: Notify on PR merged
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          MERGED_BY: ${{ github.event.pull_request.merged_by.login }}
        run: |
          pr_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${PR_NUMBER}"
          content="**PR merged** in ${GITHUB_REPOSITORY}\nTitle: ${PR_TITLE}\nNumber: ${PR_NUMBER}\nAuthor: ${PR_USER}\nMerged by: ${MERGED_BY}\n${pr_url}"
          json=$(printf '%s' "{\"content\":\"$content\"}")
          curl -s -H "Content-Type: application/json" -d "$json" "$WEBHOOK"
