---
name: Super-Linter

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  super-linter:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_WORKSPACE: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Exclude game assets, cache, and saves which are not source code:
          FILTER_REGEX_EXCLUDE: '^(game/gui/|game/audio/|game/saves/|cache/|gui/|gui/.*|game/cache/|\.rpyc$|\.rpyb$)'
          LINTER_RULES_PATH: .github/linters